//Defining our action type constants
export const SEARCH_SESSIONS_REQUEST = 'SEARCH_SESSIONS_REQUEST';
export const SEARCH_SESSIONS_SUCCESS = 'SEARCH_SESSIONS_SUCCESS';
export const SEARCH_SESSIONS_FAILURE = 'SEARCH_SESSIONS_FAILURE';
